# Generated by Django 4.2.1 on 2023-06-10 08:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("SQL", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqltutorial",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
