# Generated by Django 4.2.1 on 2023-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SQL", "0002_alter_sqltutorial_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqltutorial",
            name="content",
            field=models.TextField(),
        ),
    ]
