# Generated by Django 4.2.1 on 2023-06-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SQL", "0002_alter_database_customerid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Database",
            new_name="Customers",
        ),
    ]
