# Generated by Django 4.2.1 on 2023-07-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQL', '0004_user_user_country_user_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqltutorial',
            name='qizanswer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
