# Generated by Django 4.2.1 on 2023-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQL', '0006_alter_user_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
